"""create posts table

Revision ID: af7b0f2cb211
Revises: eb7247bb02f9
Create Date: 2026-07-19 07:12:06.891838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7b0f2cb211'
down_revision: Union[str, Sequence[str], None] = 'eb7247bb02f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalities', sa.Column('personality', sa.String(), nullable=False))
    op.drop_column('personalities', 'personalities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalities', sa.Column('personalities', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('personalities', 'personality')
    # ### end Alembic commands ###
