"""create user_personalities table

Revision ID: b93c6e28d520
Revises: cf49ee44fe88
Create Date: 2026-07-05 03:23:51.229132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93c6e28d520'
down_revision: Union[str, Sequence[str], None] = 'cf49ee44fe88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personalities_id'), 'user_personalities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_personalities_id'), table_name='user_personalities')
    op.drop_table('user_personalities')
    # ### end Alembic commands ###
