"""create personalities table

Revision ID: eb7041d159a4
Revises: 8431b7623b3d
Create Date: 2026-06-07 05:56:01.003523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7041d159a4'
down_revision: Union[str, Sequence[str], None] = '8431b7623b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personalities', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalities_id'), 'personalities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personalities_id'), table_name='personalities')
    op.drop_table('personalities')
    # ### end Alembic commands ###
